# Generated by Django 6.1.1 on 2026-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
        ('participants', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', through='participants.Registration', to='participants.participant'),
        ),
    ]
